// Dorayaki — donnees du catalogue (sorties de index.html le 10/10/2026).
// Charge AVANT le script principal (balise <script src="catalogue.js?v=…"> de index.html) :
// INV_DEFAULT et MEALS_DEFAULT (inventaire et repas de demonstration de mon ancien profil),
// RCP (catalogue de recettes, recettes communes et anciennes recettes sans creneau).
// Que des donnees : aucune fonction ici. Les tests le chargent avec le script (tests/sb.js).
const INV_DEFAULT={frigo:[
  {id:'jambon_blanc',name:'Jambon blanc',qty:600,unit:'g',urgent:1},
  {id:'jambon_poulet',name:'Jambon de poulet',qty:180,unit:'g',urgent:1},
  {id:'bacon',name:'Allumettes de bacon',qty:900,unit:'g',urgent:1},
  {id:'jambon_all',name:'Allumettes de jambon',qty:200,unit:'g',urgent:1},
  {id:'creme_liq',name:'Crème légère liquide',qty:600,unit:'mL',urgent:0},
  {id:'creme_semi',name:'Crème semi-épaisse',qty:800,unit:'g',urgent:0},
  {id:'cabillaud',name:'Panés de cabillaud',qty:2,unit:'pcs',urgent:1},
  {id:'yaourts',name:'Yaourts 0% fruits',qty:18,unit:'pots',urgent:1},
  {id:'fb_vanille',name:'Fromage blanc vanille 0%',qty:23,unit:'pots',urgent:1},
  {id:'tomates_cerises',name:'Tomates cerises',qty:200,unit:'g',urgent:1},
  {id:'fb_nature',name:'Fromage blanc 0% nature',qty:500,unit:'g',urgent:0},
  {id:'oeufs',name:'Oeufs',qty:42,unit:'pcs',urgent:0},
  {id:'avocats',name:'Avocats',qty:2,unit:'pcs',urgent:1},
  {id:'fromage_rape',name:'Fromage râpé',qty:650,unit:'g',urgent:0},
  {id:'st_moret',name:'St Morêt léger',qty:1100,unit:'g',urgent:0},
  {id:'mozzarella',name:'Billes de mozzarella',qty:300,unit:'g',urgent:1},
  {id:'creme_fraiche',name:'Crème fraîche légère',qty:2500,unit:'g',urgent:0},
  {id:'pates_pesto',name:'Pâtes fourrées pesto',qty:250,unit:'g',urgent:1},
  {id:'pates_ricotta',name:'Pâtes ricotta-épinards',qty:250,unit:'g',urgent:1},
],congelateur:[
  {id:'poulet',name:'Poulet lamelles',qty:2000,unit:'g',urgent:0},
  {id:'pizzas',name:'Pizzas De la Mama',qty:3,unit:'pcs',urgent:0},
  {id:'steaks',name:'Steaks (4 à 5% MG)',qty:10,unit:'pcs',urgent:0},
  {id:'boeuf_hache',name:'Boeuf haché (450g à 5% MG)',qty:1000,unit:'g',urgent:0},
  {id:'oignons',name:'Oignons émincés',qty:1100,unit:'g',urgent:0},
  {id:'framboises',name:'Framboises surgelées',qty:500,unit:'g',urgent:0},
  {id:'frites',name:'Frites au four',qty:500,unit:'g',urgent:0},
],placards:[
  {id:'the',name:'Thé vert / noir',qty:null,unit:'',urgent:0},
  {id:'compotes',name:'Gourdes de compotes',qty:63,unit:'pcs',urgent:0},
  {id:'ramen',name:'Ramen instantanés',qty:3,unit:'pcs',urgent:0},
  {id:'banania',name:'Banania',qty:500,unit:'g',urgent:0},
  {id:'ratatouille',name:'Ratatouille Casse-Grain',qty:2,unit:'boîtes',urgent:0},
  {id:'chili',name:'Chili mexicain Casse-Grain',qty:2,unit:'boîtes',urgent:0},
  {id:'thon',name:'Thon en conserve',qty:3,unit:'boîtes',urgent:0},
  {id:'sauce_tomate',name:'Tubes sauce tomate',qty:6,unit:'tubes',urgent:0},
  {id:'miel',name:'Miel liquide',qty:2,unit:'tubes',urgent:0},
  {id:'bouillon_poulet',name:'Bouillon poulet',qty:18,unit:'cubes',urgent:0},
  {id:'bouillon_boeuf',name:'Bouillon boeuf',qty:20,unit:'cubes',urgent:0},
  {id:'bouillon_legumes',name:'Bouillon légumes',qty:22,unit:'cubes',urgent:0},
  {id:'riz',name:'Riz Oiseaux Célestes',qty:5140,unit:'g',urgent:0},
  {id:'pates_completes',name:'Pâtes complètes',qty:1300,unit:'g',urgent:0},
  {id:'pates_blanches',name:'Pâtes blanches',qty:1000,unit:'g',urgent:0},
  {id:'pates_proteinees',name:'Pâtes protéinées',qty:500,unit:'g',urgent:0},
  {id:'amandes',name:'Amandes',qty:300,unit:'g',urgent:0},
  {id:'lait',name:'Lait sans lactose',qty:13000,unit:'ml',urgent:0},
  {id:'flocons',name:"Flocons d'avoine",qty:1700,unit:'g',urgent:0},
  {id:'cereales',name:'Céréales (Trésor, Lion...)',qty:3000,unit:'g',urgent:0},
  {id:'huile_olive',name:"Huile d'olive",qty:1000,unit:'mL',urgent:0},
  {id:'sauce_chili',name:'Sauce chili douce',qty:700,unit:'g',urgent:0},
  {id:'vinaigre_riz',name:'Vinaigre de riz',qty:200,unit:'mL',urgent:0},
  {id:'soja',name:'Sauce soja sucrée',qty:600,unit:'mL',urgent:0},
  {id:'lait_coco',name:'Lait de coco',qty:1400,unit:'mL',urgent:0},
  {id:'huile_tournesol',name:'Huile de tournesol',qty:1000,unit:'mL',urgent:0},
  {id:'bananes',name:'Bananes',qty:0,unit:'pcs',urgent:1},
  {id:'pommes',name:'Pommes',qty:6,unit:'pcs',urgent:0},
  {id:'wraps',name:'Wraps protéinés',qty:8,unit:'pcs',urgent:0},
  {id:'whey',name:'Clear whey',qty:940,unit:'g',urgent:0},
],epices:[
  {id:'curry',name:'Curry',qty:null,unit:'',urgent:0},{id:'curcuma',name:'Curcuma',qty:null,unit:'',urgent:0},
  {id:'gingembre',name:'Gingembre',qty:null,unit:'',urgent:0},{id:'ail',name:'Ail en poudre',qty:null,unit:'',urgent:0},
  {id:'poivre',name:'Poivre',qty:null,unit:'',urgent:0},{id:'sel',name:'Sel Herbamare',qty:null,unit:'',urgent:0},
  {id:'epices_it',name:'Épices italiennes',qty:null,unit:'',urgent:0},{id:'sesame',name:'Sésame doré',qty:null,unit:'',urgent:0},
  {id:'paprika',name:'Paprika',qty:null,unit:'',urgent:0},{id:'muscade',name:'Noix de muscade',qty:null,unit:'',urgent:0},
]};

const MEALS_DEFAULT={
  '2026-06-03':[{rid:'pdj_avoine',mult:1,dessert:null,customDessert:null},{rid:'poke_bowl',mult:1,dessert:null,customDessert:null},{rid:'shaker_whey',mult:1,dessert:null,customDessert:null},{rid:'gratin_gnocchis',mult:1,dessert:null,customDessert:null}],
  '2026-06-04':[{rid:'gratin_gnocchis',mult:1,dessert:null,customDessert:null},{rid:'_nuggets_04',mult:1,dessert:null,customDessert:null},{rid:'_poulet_pane_04',mult:1,dessert:null,customDessert:null}],
  '2026-06-05':[
    {rid:'saumon_riz',mult:1,dessert:'autre',customDessert:{name:'Yaourt + FB vanille',kcal:153,prot:12,gluc:24,lip:0}},
    {rid:'_karaage_05',mult:1,dessert:null,customDessert:null},
    {rid:'_poulet_pane_05',mult:1,dessert:null,customDessert:null},
  ],
  '2026-06-06':[
    {rid:'pates_prosciutto_mozza',mult:1,dessert:null,customDessert:null},
    {rid:'shaker_whey',mult:1,dessert:null,customDessert:null},
    {rid:'_diner_pizza_06',mult:1,dessert:null,customDessert:null},
  ],
  '2026-06-07':[
    // Petit-déj : bowl avoine + yaourt + framboises (~80g)
    {rid:'pdj_avoine',mult:1,dessert:'yaourt',customDessert:null},
    {rid:'_framboises_07',mult:1,dessert:null,customDessert:null},
    // Midi : cantine Disneyland
    {rid:'_repas_cantine_07',mult:1,dessert:null,customDessert:null},
    {rid:'_pates_creme_saumon_250',mult:1,dessert:'yaourt',customDessert:null},
  ],
  '2026-06-08':[
    {rid:'_pates_creme_saumon_250',mult:1,dessert:'compote',customDessert:null},
    {rid:'omelette',mult:1,dessert:'yaourt',customDessert:null},
    {rid:'_galette_sarrasin_08',mult:1,dessert:null,customDessert:null},
  ],
};

const RCP=[
  // ═══ Catalogue Liam v8 — refait le 10/10/2026 sur l'inventaire du jour ═══
  // Plats 550-700 kcal (≥ 35 g de protéines), petits-déjeuners ≤ 550. Les identifiants
  // repris gardent photos et historique ; les recettes retirées sont plus bas, sans créneau.
  {id:'liam_v6_avoine_fraises',profile:'liam',slots:['breakfast'],name:'Avoine, fromage blanc & fraises',urgent:0,ur:null,time:5,kcal:459,prot:23,gluc:72,lip:6,steps:["Verser 70 g de flocons d'avoine dans un bol.","Ajouter 200 g de fromage blanc, mélanger.","Décongeler 120 g de fraises 40 s au micro-ondes, les répartir dessus.","Filet de miel (10 g)."],used:[{id:'flocons',n:'Flocons d\'avoine',qty:70},{id:'cx_mqwm344t',n:'Fromage blanc 0% nature ou parfumé',qty:200},{id:'cx_mtot73u2',n:'Fraises surgelées',qty:120},{id:'miel',n:'Miel liquide',qty:10}],extras:[]},
  {id:'liam_v6_porridge_whey',profile:'liam',slots:['breakfast'],name:'Porridge protéiné cacao',urgent:0,ur:null,time:8,kcal:498,prot:40,gluc:62,lip:7,steps:["Chauffer 60 g de flocons dans 250 ml de lait sans lactose, 3 min à feu doux.","Hors du feu, laisser tiédir 2 min — la whey coagule dans un liquide bouillant.","Incorporer 30 g de clear whey et 15 g de Banania."],used:[{id:'flocons',n:'Flocons d\'avoine',qty:60},{id:'cx_mqwko0o6',n:'Lait sans lactose',qty:250},{id:'whey',n:'Clear whey',qty:30},{id:'banania',n:'Banania',qty:15}],extras:[]},
  {id:'liam_v7_porridge_framboises',profile:'liam',slots:['breakfast'],name:'Porridge framboises & whey',urgent:0,ur:null,time:8,kcal:478,prot:35,gluc:65,lip:7,steps:["Chauffer 60 g de flocons dans 200 ml de lait sans lactose, 3 min à feu doux.","Ajouter 100 g de framboises surgelées, 1 min pour les décongeler.","Hors du feu, laisser tiédir 2 min puis incorporer 25 g de clear whey.","Finir avec 8 g de miel."],used:[{id:'flocons',n:'Flocons d\'avoine',qty:60},{id:'cx_mqwko0o6',n:'Lait sans lactose',qty:200},{id:'cx_mqwkf3e6',n:'Framboises surgelées',qty:100},{id:'whey',n:'Clear whey',qty:25},{id:'miel',n:'Miel liquide',qty:8}],extras:[]},
  {id:'liam_v6_bol_banania',profile:'liam',slots:['breakfast','snack'],name:'Bol de Banania protéiné',urgent:0,ur:null,time:4,kcal:318,prot:31,gluc:37,lip:4,steps:["Chauffer 300 ml de lait sans lactose.","Délayer 25 g de Banania.","Laisser tiédir, puis fouetter 25 g de clear whey."],used:[{id:'cx_mqwko0o6',n:'Lait sans lactose',qty:300},{id:'banania',n:'Banania',qty:25},{id:'whey',n:'Clear whey',qty:25}],extras:[]},
  {id:'liam_v8_lion_fb_whey',profile:'liam',slots:['breakfast','snack'],name:'Fromage blanc protéiné, Lion & fraises',urgent:0,ur:null,time:4,kcal:384,prot:32,gluc:52,lip:4,steps:["Fouetter 250 g de fromage blanc avec 15 g de clear whey.","Décongeler 100 g de fraises 40 s au micro-ondes, les ajouter.","Parsemer 35 g de céréales Lion au dernier moment, pour qu'elles restent croustillantes."],used:[{id:'cx_mqwm344t',n:'Fromage blanc 0% nature ou parfumé',qty:250},{id:'whey',n:'Clear whey',qty:15},{id:'cx_mt7fuw0m',n:'lion',qty:35},{id:'cx_mtot73u2',n:'Fraises surgelées',qty:100}],extras:[]},
  {id:'liam_v6_oeufs_bacon',profile:'liam',slots:['breakfast'],name:'Œufs brouillés au bacon',urgent:0,ur:null,time:10,kcal:359,prot:35,gluc:2,lip:23,steps:["Faire revenir 60 g de bacon à sec, 3 min.","Battre 3 œufs, verser dessus, feu doux.","Remuer sans arrêt, retirer quand c'est encore crémeux.","Parsemer 20 g de râpé."],used:[{id:'oeufs',n:'Oeufs',qty:3},{id:'cx_mqwkk2as',n:'Allumettes de bacon',qty:60},{id:'cx_mqwkdso8',n:'Fromage râpé',qty:20}],extras:[]},
  {id:'liam_v6_omelette_jambon',profile:'liam',slots:['breakfast','lunch'],name:'Omelette jambon & St Morêt',urgent:0,ur:null,time:10,kcal:449,prot:44,gluc:9,lip:25,steps:["Poêler 75 g d'allumettes de jambon avec 50 g d'oignons, 4 min.","Battre 4 œufs, verser dans la poêle.","À mi-cuisson, déposer 40 g de St Morêt léger au centre.","Replier l'omelette, laisser fondre 1 min."],used:[{id:'oeufs',n:'Oeufs',qty:4},{id:'cx_ms8yrk7g',n:'Allumettes de jambon',qty:75},{id:'cx_ms8yjwau',n:'St Morêt léger',qty:40},{id:'oignons',n:'Oignons émincés',qty:50}],extras:[]},
  {id:'liam_v7_omelette_chevre',profile:'liam',slots:['breakfast','lunch'],name:'Omelette chèvre & jambon de poulet',urgent:0,ur:null,time:10,kcal:422,prot:41,gluc:6,lip:26,steps:["Battre 3 œufs avec 1 g de poivre.","Verser dans une poêle chaude, feu moyen.","Répartir 70 g de jambon de poulet en lanières et 40 g de chèvre émietté.","Replier quand le dessus est encore baveux, servir avec 100 g de tomates cerises crues."],used:[{id:'oeufs',n:'Oeufs',qty:3},{id:'cx_ms8yaett',n:'Jambon de poulet',qty:70},{id:'cx_musr6p1c',n:'Fromage de chèvre au lait pasteurisé',qty:40},{id:'cx_ms8z08jd',n:'Tomates cerises',qty:100},{id:'poivre',n:'Poivre',qty:1}],extras:[]},
  {id:'liam_v6_poulet_riz_soja',profile:'liam',slots:['lunch','dinner'],name:'Aiguillettes, riz & sauce soja',urgent:0,ur:null,time:20,kcal:626,prot:55,gluc:75,lip:11,steps:["Lancer 75 g de riz dans l'eau bouillante salée.","Saisir 200 g d'aiguillettes dans 5 ml d'huile, 6 min à feu vif.","Ajouter 60 g d'oignons, 3 min.","Déglacer avec 20 ml de soja, réduire 1 min.","Servir sur le riz, parsemer 4 g de sésame."],used:[{id:'cx_mqwkfekl',n:'Aiguillettes de poulet',qty:200},{id:'riz',n:'Riz Oiseaux Célestes',qty:75},{id:'soja',n:'Sauce soja sucrée',qty:20},{id:'oignons',n:'Oignons émincés',qty:60},{id:'sesame',n:'Sésame doré',qty:4},{id:'huile_olive',n:'Huile d\'olive',qty:5}],extras:[]},
  {id:'liam_v8_poulet_chili_doux',profile:'liam',slots:['lunch','dinner'],name:'Poulet sauce chili douce & riz',urgent:0,ur:null,time:20,kcal:584,prot:53,gluc:78,lip:6,steps:["Lancer 70 g de riz.","Saisir 200 g d'aiguillettes à sec dans une poêle antiadhésive, 6 min.","Ajouter 50 g d'oignons, 3 min.","Hors du feu, enrober de 30 g de sauce chili douce détendue avec 10 ml de vinaigre de riz.","Servir sur le riz, 4 g de sésame."],used:[{id:'cx_mqwkfekl',n:'Aiguillettes de poulet',qty:200},{id:'riz',n:'Riz Oiseaux Célestes',qty:70},{id:'sauce_chili',n:'Sauce chili douce',qty:30},{id:'vinaigre_riz',n:'Vinaigre de riz',qty:10},{id:'oignons',n:'Oignons émincés',qty:50},{id:'sesame',n:'Sésame doré',qty:4}],extras:[]},
  {id:'liam_v6_poulet_curry_coco',profile:'liam',slots:['lunch','dinner'],name:'Poulet curry-coco & riz',urgent:0,ur:null,time:25,kcal:650,prot:55,gluc:59,lip:21,steps:["Lancer 60 g de riz.","Faire suer 70 g d'oignons 3 min.","Ajouter 200 g d'aiguillettes, saisir 5 min.","Verser 80 ml de lait de coco, 6 g de curry, 3 g de gingembre, 1 cube de bouillon.","Mijoter 10 min à couvert."],used:[{id:'cx_mqwkfekl',n:'Aiguillettes de poulet',qty:200},{id:'riz',n:'Riz Oiseaux Célestes',qty:60},{id:'lait_coco',n:'Lait de coco',qty:80},{id:'oignons',n:'Oignons émincés',qty:70},{id:'curry',n:'Curry',qty:6},{id:'gingembre',n:'Gingembre',qty:3},{id:'bouillon_poulet',n:'Bouillon poulet',qty:1}],extras:[]},
  {id:'liam_v8_pates_poulet_parmesan',profile:'liam',slots:['lunch','dinner'],name:'Pâtes complètes, poulet, crème & parmesan',urgent:0,ur:null,time:20,kcal:588,prot:50,gluc:60,lip:15,steps:["Lancer 80 g de pâtes complètes.","Saisir 150 g d'aiguillettes en dés à sec, 6 min, avec 50 g d'oignons.","Hors du feu, ajouter 50 g de crème fraîche légère et 2 g d'épices italiennes.","Mélanger aux pâtes, finir avec 10 g de parmesan râpé."],used:[{id:'pates_completes',n:'Pâtes complètes',qty:80},{id:'cx_mqwkfekl',n:'Aiguillettes de poulet',qty:150},{id:'cx_mqwm5mzs',n:'Crème fraîche légère',qty:50},{id:'oignons',n:'Oignons émincés',qty:50},{id:'cx_musr7n63',n:'Parmigiano Reggiano',qty:10},{id:'epices_it',n:'Épices italiennes',qty:2}],extras:[]},
  {id:'liam_v6_poulet_pane_maison',profile:'liam',slots:['lunch','dinner'],name:'Poulet pané maison & frites',urgent:0,ur:null,time:30,kcal:651,prot:63,gluc:58,lip:16,steps:["Four à 200 °C, 130 g de frites pour 25 min.","Battre 1 œuf, y tremper 200 g d'aiguillettes, rouler dans 40 g de panure.","Enfourner les aiguillettes panées à mi-cuisson des frites, 12 min.","Servir avec 25 ml de sauce Honey Mustard."],used:[{id:'cx_mqwkfekl',n:'Aiguillettes de poulet',qty:200},{id:'cx_mqwkhtgi',n:'Panure',qty:40},{id:'oeufs',n:'Oeufs',qty:1},{id:'frites',n:'Frites au four',qty:130},{id:'cx_mtoubuqk',n:'Honey Mustard Dressing sauce',qty:25}],extras:[]},
  {id:'liam_v6_karaage_riz',profile:'liam',slots:['lunch','dinner'],name:'Poulet karaage, riz & sauce soja',urgent:0,ur:null,time:25,kcal:668,prot:40,gluc:79,lip:20,steps:["Préchauffer le four à 200 °C, enfourner 200 g de karaage 20 min.","Lancer 55 g de riz.","Poêler 40 g d'oignons 3 min.","Dresser, arroser de 15 ml de soja et parsemer 4 g de sésame."],used:[{id:'cx_ms8y4spg',n:'Poulet Karaage',qty:200},{id:'riz',n:'Riz Oiseaux Célestes',qty:55},{id:'soja',n:'Sauce soja sucrée',qty:15},{id:'sesame',n:'Sésame doré',qty:4},{id:'oignons',n:'Oignons émincés',qty:40}],extras:[]},
  {id:'liam_v6_panko_frites',profile:'liam',slots:['lunch','dinner'],name:'Poulet panko & frites au four',urgent:0,ur:null,time:28,kcal:669,prot:38,gluc:63,lip:29,steps:["Four à 200 °C. Enfourner 130 g de frites 25 min.","Ajouter 200 g de poulet panko à mi-cuisson, 14 min.","Servir avec 30 g de sauce BBQ zéro."],used:[{id:'cx_ms8y5it1',n:'Poulet Panko',qty:200},{id:'frites',n:'Frites au four',qty:130},{id:'cx_musrurg0',n:'BBQ ZERO',qty:30}],extras:[]},
  {id:'liam_v8_cuisse_panee_frites',profile:'liam',slots:['lunch','dinner'],name:'Haut de cuisse pané, frites & tomates',urgent:0,ur:null,time:28,kcal:642,prot:36,gluc:61,lip:26,steps:["Four à 200 °C. Enfourner 230 g de haut de cuisse pané et 100 g de frites, 25 min.","Servir avec 100 g de tomates cerises crues coupées en deux.","Accompagner de 20 g de sauce BBQ zéro."],used:[{id:'cx_mtdiah8m',n:'Haut de cuisse de poulet pané',qty:230},{id:'frites',n:'Frites au four',qty:100},{id:'cx_ms8z08jd',n:'Tomates cerises',qty:100},{id:'cx_musrurg0',n:'BBQ ZERO',qty:20}],extras:[]},
  {id:'liam_v6_ramen_poulet',profile:'liam',slots:['lunch','dinner'],name:'Ramen au poulet et bouillon',urgent:0,ur:null,time:15,kcal:522,prot:56,gluc:47,lip:11,steps:["Porter 500 ml d'eau à ébullition avec 1 cube de bouillon poulet.","Pocher 1 œuf 6 min, réserver — jaune coulant.","Saisir 180 g d'aiguillettes à part, 6 min, puis 50 g d'oignons.","Cuire 100 g de ramen 3 min dans le bouillon.","Dresser, 15 ml de soja, l'œuf coupé en deux, 4 g de sésame."],used:[{id:'ramen',n:'Ramen instantanés',qty:100},{id:'cx_mqwkfekl',n:'Aiguillettes de poulet',qty:180},{id:'oeufs',n:'Oeufs',qty:1},{id:'oignons',n:'Oignons émincés',qty:50},{id:'bouillon_poulet',n:'Bouillon poulet',qty:1},{id:'soja',n:'Sauce soja sucrée',qty:15},{id:'sesame',n:'Sésame doré',qty:4}],extras:[]},
  {id:'liam_v6_bolo_completes',profile:'liam',slots:['lunch','dinner'],name:'Pâtes complètes à la bolognaise',urgent:0,ur:null,time:25,kcal:622,prot:45,gluc:73,lip:15,steps:["Lancer 75 g de pâtes complètes.","Faire revenir 60 g d'oignons à sec avec un fond d'eau, 3 min.","Ajouter 150 g de bœuf haché, écraser à la cuillère, 6 min.","Verser 150 g de sauce tomate et 4 g d'épices italiennes, mijoter 10 min.","Servir avec 10 g de fromage râpé."],used:[{id:'pates_completes',n:'Pâtes complètes',qty:75},{id:'boeuf_hache',n:'Boeuf haché (450g à 5% MG)',qty:150},{id:'sauce_tomate',n:'Tubes sauce tomate',qty:150},{id:'oignons',n:'Oignons émincés',qty:60},{id:'epices_it',n:'Épices italiennes',qty:4},{id:'cx_mqwkdso8',n:'Fromage râpé',qty:10}],extras:[]},
  {id:'liam_v6_chili_riz',profile:'liam',slots:['lunch','dinner'],name:'Chili au bœuf & riz',urgent:0,ur:null,time:20,kcal:637,prot:46,gluc:82,lip:13,steps:["Lancer 65 g de riz.","Saisir 150 g de bœuf haché avec 50 g d'oignons, 7 min.","Ajouter une demi-boîte de chili (environ 215 g) et 3 g de paprika ; garder l'autre moitié au frais pour le lendemain.","Mijoter 8 min à feu doux."],used:[{id:'chili',n:'Chili mexicain Casse-Grain',qty:0.5},{id:'boeuf_hache',n:'Boeuf haché (450g à 5% MG)',qty:150},{id:'riz',n:'Riz Oiseaux Célestes',qty:65},{id:'oignons',n:'Oignons émincés',qty:50},{id:'paprika',n:'Paprika',qty:3}],extras:[]},
  {id:'liam_v6_steak_ratatouille',profile:'liam',slots:['lunch','dinner'],name:'Steak, ratatouille & lentilles',urgent:0,ur:null,time:15,kcal:561,prot:55,gluc:41,lip:20,steps:["Réchauffer 200 g de ratatouille et 130 g de lentilles à la poêle, 5 min.","Cuire 2 steaks 3 min par face.","Assaisonner de 2 g d'ail en poudre."],used:[{id:'steaks',n:'Steaks (5% MG)',qty:2},{id:'ratatouille',n:'Ratatouille Casse-Grain',qty:200},{id:'cx_mqwm1niv',n:'lentilles casse grains',qty:130},{id:'ail',n:'Ail en poudre',qty:2}],extras:[]},
  {id:'liam_v6_steak_frites',profile:'liam',slots:['lunch','dinner'],name:'Steak & frites au four',urgent:0,ur:null,time:30,kcal:608,prot:46,gluc:46,lip:24,steps:["Enfourner 200 g de frites à 200 °C, 25 min.","Cuire 2 steaks 3 min par face en fin de cuisson.","Servir avec 30 g de sauce BBQ zéro."],used:[{id:'steaks',n:'Steaks (5% MG)',qty:2},{id:'frites',n:'Frites au four',qty:200},{id:'cx_musrurg0',n:'BBQ ZERO',qty:30}],extras:[]},
  {id:'liam_v6_boulettes_puree',profile:'liam',slots:['lunch','dinner'],name:'Boulettes IKEA, pâtes protéinées & sauce crème',urgent:0,ur:null,time:22,kcal:663,prot:36,gluc:57,lip:32,steps:["Lancer 70 g de pâtes 21 g de protéines.","Poêler 130 g de boulettes 10 min en les retournant.","Retirer, faire suer 50 g d'oignons dans la même poêle.","Verser 40 ml de crème liquide, 1 cube de bouillon émietté, 1 g de muscade ; remettre les boulettes 5 min.","Servir sur les pâtes avec 10 g de parmesan râpé."],used:[{id:'cx_mtos3ak5',n:'Huvudroll - Meatballs (boulettes IKEA)',qty:130},{id:'cx_mtou24qu',n:'pâtes 21 g protein',qty:70},{id:'creme_liq',n:'Crème légère liquide',qty:40},{id:'oignons',n:'Oignons émincés',qty:50},{id:'bouillon_legumes',n:'Bouillon légumes',qty:1},{id:'muscade',n:'Noix de muscade',qty:1},{id:'cx_musr7n63',n:'Parmigiano Reggiano',qty:10}],extras:[]},
  {id:'liam_v6_saumon_riz',profile:'liam',slots:['lunch','dinner'],name:'Bowl saumon, riz, œuf & tomates',urgent:0,ur:null,time:20,kcal:571,prot:36,gluc:67,lip:17,steps:["Lancer 70 g de riz. Cuire 1 œuf 7 min, le passer sous l'eau froide.","Saisir 120 g de saumon côté peau à sec, 4 min, retourner 3 min.","Dresser le riz, le saumon émietté, l'œuf coupé en deux et 100 g de tomates cerises crues.","Arroser de 15 ml de soja, 4 g de sésame."],used:[{id:'cx_ms8y6yk4',n:'Saumon',qty:120},{id:'riz',n:'Riz Oiseaux Célestes',qty:70},{id:'oeufs',n:'Oeufs',qty:1},{id:'cx_ms8z08jd',n:'Tomates cerises',qty:100},{id:'soja',n:'Sauce soja sucrée',qty:15},{id:'sesame',n:'Sésame doré',qty:4}],extras:[]},
  {id:'liam_v6_thon_pates',profile:'liam',slots:['lunch','dinner'],name:'Pâtes au thon et à la tomate',urgent:0,ur:null,time:18,kcal:683,prot:55,gluc:75,lip:20,steps:["Lancer 75 g de pâtes.","Faire suer 50 g d'oignons à sec avec un fond d'eau.","Ajouter 120 g de thon égoutté et 140 g de sauce tomate, 6 min.","Mélanger aux pâtes, 4 g d'épices italiennes."],used:[{id:'pates_blanches',n:'Pâtes blanches',qty:75},{id:'thon',n:'Thon en conserve',qty:120},{id:'sauce_tomate',n:'Tubes sauce tomate',qty:140},{id:'oignons',n:'Oignons émincés',qty:50},{id:'epices_it',n:'Épices italiennes',qty:4}],extras:[]},
  {id:'liam_v7_pates21_thon_citron',profile:'liam',slots:['lunch','dinner'],name:'Pâtes protéinées, thon & crème citronnée',urgent:0,ur:null,time:15,kcal:595,prot:57,gluc:68,lip:10,steps:["Cuire 100 g de pâtes 21 g de protéines.","Faire suer 40 g d'oignons, 3 min.","Hors du feu, mélanger 120 g de thon au naturel émietté, 50 g de crème fraîche légère et 10 ml de jus de citron.","Lier aux pâtes égouttées, 1 g de poivre."],used:[{id:'cx_mtou24qu',n:'pâtes 21 g protein',qty:100},{id:'cx_musswwix',n:'Thon entier au naturel',qty:120},{id:'cx_mqwm5mzs',n:'Crème fraîche légère',qty:50},{id:'oignons',n:'Oignons émincés',qty:40},{id:'cx_mtotj6yk',n:'Citron / Citron vert',qty:10},{id:'poivre',n:'Poivre',qty:1}],extras:[]},
  {id:'liam_v6_pates_prot_bacon',profile:'liam',slots:['lunch','dinner'],name:'Pâtes protéinées, bacon & crème',urgent:0,ur:null,time:15,kcal:641,prot:44,gluc:67,lip:21,steps:["Lancer 90 g de pâtes protéinées.","Faire dorer 100 g de bacon à sec avec 40 g d'oignons, 5 min.","Hors du feu, ajouter 60 g de crème fraîche légère.","Mélanger aux pâtes, finir avec 20 g de râpé."],used:[{id:'pates_proteinees',n:'Pâtes protéinées',qty:90},{id:'cx_mqwkk2as',n:'Allumettes de bacon',qty:100},{id:'cx_mqwm5mzs',n:'Crème fraîche légère',qty:60},{id:'cx_mqwkdso8',n:'Fromage râpé',qty:20},{id:'oignons',n:'Oignons émincés',qty:40}],extras:[]},
  {id:'liam_v8_riz_bacon_oeufs',profile:'liam',slots:['lunch','dinner'],name:'Riz sauté bacon & œufs',urgent:0,ur:null,time:20,kcal:585,prot:36,gluc:67,lip:18,steps:["Cuire 70 g de riz, l'égoutter.","Faire revenir 60 g de bacon et 60 g d'oignons, 3 min, sans matière grasse.","Ajouter le riz, faire sauter 3 min à feu vif.","Pousser sur le côté, brouiller 3 œufs dans la poêle, mélanger.","Déglacer avec 10 ml de sauce soja."],used:[{id:'riz',n:'Riz Oiseaux Célestes',qty:70},{id:'cx_mqwkk2as',n:'Allumettes de bacon',qty:60},{id:'oeufs',n:'Oeufs',qty:3},{id:'oignons',n:'Oignons émincés',qty:60},{id:'soja',n:'Sauce soja sucrée',qty:10}],extras:[]},
  {id:'liam_v6_gnocchi_bacon',profile:'liam',slots:['lunch','dinner'],name:'Gnocchis poêlés, bacon & crème',urgent:0,ur:null,time:15,kcal:616,prot:36,gluc:71,lip:20,steps:["Poêler 180 g de gnocchis à sec dans une poêle antiadhésive, 6 min jusqu'à ce qu'ils dorent.","Ajouter 130 g de bacon et 50 g d'oignons, 4 min.","Hors du feu, lier avec 40 g de crème semi-épaisse."],used:[{id:'cx_mtot8zeh',n:'Gnocchi à poêler',qty:180},{id:'cx_mqwkk2as',n:'Allumettes de bacon',qty:130},{id:'creme_semi',n:'Crème semi-épaisse',qty:40},{id:'oignons',n:'Oignons émincés',qty:50}],extras:[]},
  {id:'liam_v7_gnocchis_fj_salade',profile:'liam',slots:['lunch','dinner'],name:'Gnocchis fromage-jambon & jambon de poulet',urgent:0,ur:null,time:10,kcal:677,prot:41,gluc:80,lip:20,steps:["Poêler 250 g de gnocchis fromage-jambon 6 min, jusqu'à ce qu'ils dorent.","Ajouter 100 g de jambon de poulet en lanières, 1 min.","Servir avec 120 g de tomates cerises crues."],used:[{id:'cx_mtot8746',n:'Gnocchis fromage jambon',qty:250},{id:'cx_ms8yaett',n:'Jambon de poulet',qty:100},{id:'cx_ms8z08jd',n:'Tomates cerises',qty:120}],extras:[]},
  {id:'liam_v6_tortellini_viande',profile:'liam',slots:['lunch','dinner'],name:'Tortellini viande, crème & tomates crues',urgent:0,ur:null,time:12,kcal:695,prot:35,gluc:94,lip:20,steps:["Cuire 170 g de tortellini 4 min.","Chauffer 40 g de crème fraîche avec 3 g d'épices italiennes.","Mélanger avec 60 g de jambon de poulet en lanières, ajouter 15 g de râpé.","Servir avec 120 g de tomates cerises crues, coupées en deux, à côté."],used:[{id:'cx_mtosny0o',n:'tortellini viande',qty:170},{id:'cx_mqwm5mzs',n:'Crème fraîche légère',qty:40},{id:'cx_mqwkdso8',n:'Fromage râpé',qty:15},{id:'cx_ms8yaett',n:'Jambon de poulet',qty:60},{id:'cx_ms8z08jd',n:'Tomates cerises',qty:120},{id:'epices_it',n:'Épices italiennes',qty:3}],extras:[]},
  {id:'liam_v8_tortellini_prosciutto',profile:'liam',slots:['lunch','dinner'],name:'Tortellini prosciutto, jambon & parmesan',urgent:0,ur:null,time:10,kcal:631,prot:40,gluc:73,lip:20,steps:["Cuire 150 g de tortellini prosciutto 3 min, égoutter en gardant un fond d'eau.","Mélanger avec 80 g de jambon blanc en lanières et 2 g d'épices italiennes.","Finir avec 10 g de parmesan râpé.","Servir avec 100 g de tomates cerises crues."],used:[{id:'cx_ms8zdyrx',n:'Tortellini Prosciutto',qty:150},{id:'cx_ms8y98k4',n:'Jambon blanc',qty:80},{id:'cx_musr7n63',n:'Parmigiano Reggiano',qty:10},{id:'cx_ms8z08jd',n:'Tomates cerises',qty:100},{id:'epices_it',n:'Épices italiennes',qty:2}],extras:[]},
  {id:'liam_v7_pates_comte_jambon',profile:'liam',slots:['lunch','dinner'],name:'Pâtes fraîches au Comté, jambon & tomates',urgent:0,ur:null,time:8,kcal:695,prot:55,gluc:62,lip:24,steps:["Cuire 180 g de pâtes fraîches au Comté 3 min.","Faire dorer 150 g d'allumettes de jambon à sec, 3 min.","Mélanger aux pâtes avec 1 g de poivre.","Servir avec 100 g de tomates cerises crues coupées en deux."],used:[{id:'cx_musrmhdl',n:'Pâtes fraiches au Comté AOP',qty:180},{id:'cx_ms8yrk7g',n:'Allumettes de jambon',qty:150},{id:'cx_ms8z08jd',n:'Tomates cerises',qty:100},{id:'poivre',n:'Poivre',qty:1}],extras:[]},
  {id:'liam_v7_pates_boursin_poulet',profile:'liam',slots:['lunch','dinner'],name:'Pâtes fraîches Boursin & poulet',urgent:0,ur:null,time:12,kcal:673,prot:53,gluc:56,lip:25,steps:["Saisir 150 g d'aiguillettes de poulet coupées en dés dans 5 ml d'huile, 6 min.","Cuire 180 g de pâtes fraîches au Boursin 3 min.","Mélanger les aiguillettes aux pâtes égouttées.","Servir avec 100 g de tomates cerises crues."],used:[{id:'cx_musrm6wj',n:'Pâtes fraîches au fromage Boursin® Ail et fines herbes',qty:180},{id:'cx_mqwkfekl',n:'Aiguillettes de poulet',qty:150},{id:'huile_olive',n:'Huile d\'olive',qty:5},{id:'cx_ms8z08jd',n:'Tomates cerises',qty:100}],extras:[]},
  {id:'liam_v8_pizza_jambon',profile:'liam',slots:['lunch','dinner'],name:'Demi-pizza, jambon & tomates cerises',urgent:0,ur:null,time:15,kcal:645,prot:36,gluc:69,lip:23,steps:["Cuire une pizza De la Mama au four selon le paquet et n'en servir que la moitié ; garder l'autre pour le lendemain.","À la sortie du four, ajouter 60 g de jambon blanc en lanières.","Servir avec 100 g de tomates cerises crues."],used:[{id:'pizzas',n:'Pizzas De la Mama',qty:0.5},{id:'cx_ms8y98k4',n:'Jambon blanc',qty:60},{id:'cx_ms8z08jd',n:'Tomates cerises',qty:100}],extras:[]},
  {id:'liam_v6_mozza_tomates',profile:'liam',slots:['lunch','snack'],name:'Mozzarella, tomates crues & jambon',urgent:0,ur:null,time:8,kcal:525,prot:43,gluc:9,lip:35,steps:["Égoutter 125 g de billes de mozzarella.","Couper 150 g de tomates cerises en deux, crues.","Disposer avec 100 g de jambon blanc, arroser de 8 ml d'huile d'olive et 2 g d'épices."],used:[{id:'cx_mqwkli92',n:'Billes de mozzarella',qty:125},{id:'cx_ms8z08jd',n:'Tomates cerises',qty:150},{id:'cx_ms8y98k4',n:'Jambon blanc',qty:100},{id:'huile_olive',n:'Huile d\'olive',qty:8},{id:'epices_it',n:'Épices italiennes',qty:2}],extras:[]},
  {id:'liam_v6_shaker_whey',profile:'liam',slots:['snack'],name:'Shaker clear whey',urgent:0,ur:null,time:2,kcal:102,prot:23,gluc:2,lip:0,steps:["30 g de clear whey dans 400 ml d'eau froide, secouer."],used:[{id:'whey',n:'Clear whey',qty:30}],extras:[]},
  {id:'liam_v6_fb_fraises',profile:'liam',slots:['snack'],name:'Fromage blanc & fraises',urgent:0,ur:null,time:3,kcal:222,prot:17,gluc:33,lip:2,steps:["250 g de fromage blanc dans un bol.","Ajouter 120 g de fraises décongelées et 8 g de miel."],used:[{id:'cx_mqwm344t',n:'Fromage blanc 0% nature ou parfumé',qty:250},{id:'cx_mtot73u2',n:'Fraises surgelées',qty:120},{id:'miel',n:'Miel liquide',qty:8}],extras:[]},
  {id:'liam_v7_yaourt_grec_framboises',profile:'liam',slots:['snack','breakfast'],name:'Fromage blanc, framboises & amandes',urgent:0,ur:null,time:3,kcal:250,prot:17,gluc:28,lip:9,steps:["200 g de fromage blanc dans un bol.","Ajouter 80 g de framboises décongelées 40 s au micro-ondes.","Parsemer 15 g d'amandes concassées."],used:[{id:'cx_mqwm344t',n:'Fromage blanc 0% nature ou parfumé',qty:200},{id:'cx_mqwkf3e6',n:'Framboises surgelées',qty:80},{id:'cx_mqwlzzup',n:'Amandes',qty:15}],extras:[]},
  {id:'liam_v8_fb_compote_amandes',profile:'liam',slots:['snack'],name:'Fromage blanc, compote & amandes',urgent:0,ur:null,time:3,kcal:231,prot:16,gluc:30,lip:6,steps:["200 g de fromage blanc dans un bol.","Ajouter un pot de compote.","Parsemer 10 g d'amandes."],used:[{id:'cx_mqwm344t',n:'Fromage blanc 0% nature ou parfumé',qty:200},{id:'cx_ms8zf2k9',n:'Compotes',qty:1},{id:'cx_mqwlzzup',n:'Amandes',qty:10}],extras:[]},
  {id:'liam_v8_thon_stmoret_tomates',profile:'liam',slots:['snack'],name:'Rillettes de thon au St Morêt & tomates cerises',urgent:0,ur:null,time:5,kcal:171,prot:27,gluc:6,lip:4,steps:["Écraser 80 g de thon au naturel avec 40 g de St Morêt léger et 5 ml de citron.","Ajouter 1 g de poivre.","Servir avec 100 g de tomates cerises crues pour tremper."],used:[{id:'cx_musswwix',n:'Thon entier au naturel',qty:80},{id:'cx_ms8yjwau',n:'St Morêt léger',qty:40},{id:'cx_mtotj6yk',n:'Citron / Citron vert',qty:5},{id:'cx_ms8z08jd',n:'Tomates cerises',qty:100},{id:'poivre',n:'Poivre',qty:1}],extras:[]},
  {id:'liam_v8_oeufs_durs_tomates',profile:'liam',slots:['snack'],name:'Œufs durs & tomates cerises',urgent:0,ur:null,time:12,kcal:162,prot:14,gluc:4,lip:10,steps:["Cuire 2 œufs 9 min dans l'eau bouillante, refroidir.","Servir avec 100 g de tomates cerises crues et une pincée d'Herbamare."],used:[{id:'oeufs',n:'Oeufs',qty:2},{id:'cx_ms8z08jd',n:'Tomates cerises',qty:100},{id:'sel',n:'Sel Herbamare',qty:1}],extras:[]},
  {id:'liam_v6_soupe_potiron',profile:'liam',slots:['snack','dinner'],name:'Soupe potiron & râpé',urgent:0,ur:null,time:6,kcal:211,prot:7,gluc:20,lip:10,steps:["Réchauffer 400 ml de soupe potiron-Kiri.","Parsemer 15 g de fromage râpé au moment de servir."],used:[{id:'cx_mrvi04ju',n:'Soupe - Potiron et Kiri',qty:400},{id:'cx_mqwkdso8',n:'Fromage râpé',qty:15}],extras:[]},
  {id:'liam_v6_tomates_bacon',profile:'liam',slots:['snack'],name:'Tomates cerises crues & bacon poêlé',urgent:0,ur:null,time:5,kcal:101,prot:13,gluc:6,lip:3,steps:["Faire dorer 60 g de bacon à sec, 4 min, laisser tiédir.","Couper 150 g de tomates cerises en deux, crues.","Mélanger au dernier moment pour qu'elles restent fraîches."],used:[{id:'cx_ms8z08jd',n:'Tomates cerises',qty:150},{id:'cx_mqwkk2as',n:'Allumettes de bacon',qty:60}],extras:[]},
  {id:'liam_v6_pomme_amandes',profile:'liam',slots:['snack'],name:'Pomme & amandes',urgent:0,ur:null,time:2,kcal:211,prot:5,gluc:29,lip:10,steps:["Couper une pomme en quartiers.","Compter 20 g d'amandes."],used:[{id:'pommes',n:'Pommes',qty:1},{id:'cx_mqwlzzup',n:'Amandes',qty:20}],extras:[]},
  // ── Anciennes recettes Liam : sans creneau, pour que les repas deja
  //    enregistres gardent leur nom et leurs macros ──
  // retirees le 10/10/2026 (ingredient plus en stock)
  {id:'liam_v6_nouilles_poulet',slots:[],name:'Nouilles sautées au poulet',kcal:557,prot:59,gluc:44,lip:14,steps:[],used:[],extras:[]},
  {id:'liam_v6_carbonara_surgelee',slots:[],name:'Pâtes carbonara & poulet',kcal:636,prot:54,gluc:46,lip:26,steps:[],used:[],extras:[]},
  {id:'liam_v6_concombre_stmoret',slots:[],name:'Concombre & St Morêt léger',kcal:126,prot:8,gluc:15,lip:5,steps:[],used:[],extras:[]},
  {id:'liam_v7_riz_chorizo_oeufs',slots:[],name:'Riz sauté chorizo & œufs',kcal:660,prot:34,gluc:64,lip:29,steps:[],used:[],extras:[]},
  {id:'liam_v7_thon_stmoret_concombre',slots:[],name:'Rillettes de thon au St Morêt & concombre',kcal:175,prot:28,gluc:8,lip:4,steps:[],used:[],extras:[]},
  {id:'liam_v5_avoine_fb',slots:[],name:'Avoine, fromage blanc & framboises',kcal:466,prot:23,gluc:77,lip:7,steps:[],used:[],extras:[]},
  {id:'liam_v5_porridge_whey',slots:[],name:'Porridge protéiné cacao',kcal:572,prot:43,gluc:74,lip:9,steps:[],used:[],extras:[]},
  {id:'liam_v5_oeufs_bacon',slots:[],name:'Œufs brouillés au bacon',kcal:382,prot:37,gluc:3,lip:25,steps:[],used:[],extras:[]},
  {id:'liam_v5_bol_banania',slots:[],name:'Bol de Banania protéiné',kcal:318,prot:31,gluc:37,lip:4,steps:[],used:[],extras:[]},
  {id:'liam_v5_poulet_riz_soja',slots:[],name:'Aiguillettes, riz & sauce soja',kcal:721,prot:70,gluc:70,lip:16,steps:[],used:[],extras:[]},
  {id:'liam_v5_poulet_coco_curry',slots:[],name:'Poulet curry-coco & riz',kcal:891,prot:71,gluc:75,lip:34,steps:[],used:[],extras:[]},
  {id:'liam_v5_poulet_pane_frites',slots:[],name:'Poulet pané maison & frites au four',kcal:893,prot:79,gluc:86,lip:22,steps:[],used:[],extras:[]},
  {id:'liam_v5_poulet_ramen',slots:[],name:'Ramen au poulet et bouillon',kcal:547,prot:61,gluc:40,lip:14,steps:[],used:[],extras:[]},
  {id:'liam_v5_bolo_completes',slots:[],name:'Pâtes complètes à la bolognaise',kcal:787,prot:51,gluc:89,lip:23,steps:[],used:[],extras:[]},
  {id:'liam_v5_chili_riz',slots:[],name:'Chili au bœuf & riz',kcal:546,prot:41,gluc:73,lip:10,steps:[],used:[],extras:[]},
  {id:'liam_v5_steak_ratatouille',slots:[],name:'Steak, ratatouille & lentilles',kcal:555,prot:55,gluc:40,lip:20,steps:[],used:[],extras:[]},
  {id:'liam_v5_steak_frites',slots:[],name:'Steak & frites au four',kcal:654,prot:46,gluc:59,lip:24,steps:[],used:[],extras:[]},
  {id:'liam_v5_thon_pates',slots:[],name:'Pâtes au thon et à la tomate',kcal:816,prot:58,gluc:93,lip:25,steps:[],used:[],extras:[]},
  {id:'liam_v5_pates_prot_bacon',slots:[],name:'Pâtes protéinées, bacon & crème',kcal:612,prot:44,gluc:61,lip:21,steps:[],used:[],extras:[]},
  {id:'liam_v5_gnocchis_bacon',slots:[],name:'Gnocchis poêlés, bacon & crème',kcal:935,prot:39,gluc:123,lip:31,steps:[],used:[],extras:[]},
  {id:'liam_v5_tortellini_creme',slots:[],name:'Tortellini Prosciutto à la crème',kcal:1009,prot:41,gluc:122,lip:39,steps:[],used:[],extras:[]},
  {id:'liam_v5_riz_saute_oeuf',slots:[],name:'Riz sauté au bœuf et à l\'œuf',kcal:689,prot:45,gluc:71,lip:25,steps:[],used:[],extras:[]},
  {id:'liam_v5_shaker_whey',slots:[],name:'Shaker clear whey',kcal:102,prot:23,gluc:2,lip:0,steps:[],used:[],extras:[]},
  {id:'liam_v5_fb_framboises',slots:[],name:'Fromage blanc & framboises',kcal:230,prot:17,gluc:38,lip:2,steps:[],used:[],extras:[]},
  {id:'liam_v5_soupe_potiron',slots:[],name:'Soupe potiron & Kiri',kcal:211,prot:7,gluc:20,lip:10,steps:[],used:[],extras:[]},
  {id:'liam_v5_tomates_bacon',slots:[],name:'Tomates cerises & bacon poêlé',kcal:106,prot:14,gluc:6,lip:3,steps:[],used:[],extras:[]},
  {id:'liam_v5_pomme_whey',slots:[],name:'Pomme & shaker vanille',kcal:180,prot:20,gluc:27,lip:1,steps:[],used:[],extras:[]},
  // ── Anciennes recettes Liam : conservees sans slot pour que les repas
  //    deja enregistres gardent leur nom et leurs macros ──
  {id:'liam_v4_bowl_avoine',slots:[],name:'Bowl d\'avoine, fromage blanc & framboises',kcal:472,prot:25,gluc:75,lip:7,steps:[],used:[],extras:[]},
  {id:'liam_v4_porridge_whey',slots:[],name:'Porridge protéiné banane-cannelle',kcal:620,prot:44,gluc:89,lip:9,steps:[],used:[],extras:[]},
  {id:'liam_v4_oeufs_bacon',slots:[],name:'Œufs brouillés, bacon & fromage râpé',kcal:613,prot:57,gluc:4,lip:41,steps:[],used:[],extras:[]},
  {id:'liam_v4_aiguillettes_riz',slots:[],name:'Aiguillettes de poulet, riz & sauce soja',kcal:714,prot:71,gluc:84,lip:8,steps:[],used:[],extras:[]},
  {id:'liam_v4_panko_frites',slots:[],name:'Poulet Panko, frites au four & sauce chili',kcal:803,prot:42,gluc:86,lip:32,steps:[],used:[],extras:[]},
  {id:'liam_v4_karaage_riz',slots:[],name:'Poulet Karaage, riz & sauce soja',kcal:830,prot:47,gluc:106,lip:23,steps:[],used:[],extras:[]},
  {id:'liam_v4_pates_bolo',slots:[],name:'Pâtes complètes à la bolognaise',kcal:731,prot:48,gluc:98,lip:13,steps:[],used:[],extras:[]},
  {id:'liam_v4_pates_prot_jambon',slots:[],name:'Pâtes protéinées, jambon de poulet & crème',kcal:672,prot:56,gluc:84,lip:12,steps:[],used:[],extras:[]},
  {id:'liam_v4_ravioli_4fromages',slots:[],name:'Ravioli 4 fromages & jambon poêlé',kcal:1029,prot:59,gluc:114,lip:36,steps:[],used:[],extras:[]},
  {id:'liam_v4_tortellini',slots:[],name:'Tortellini Prosciutto, tomates cerises & parmesan',kcal:930,prot:39,gluc:118,lip:33,steps:[],used:[],extras:[]},
  {id:'liam_v4_gnocchi_raclette',slots:[],name:'Gnocchi à poêler raclette & bacon',kcal:968,prot:48,gluc:110,lip:37,steps:[],used:[],extras:[]},
  {id:'liam_v4_gnocchis_bacon',slots:[],name:'Gnocchis poêlés à la crème et au bacon',kcal:710,prot:36,gluc:93,lip:21,steps:[],used:[],extras:[]},
  {id:'liam_v4_saumon_riz',slots:[],name:'Saumon, riz vinaigré & concombre',kcal:628,prot:37,gluc:86,lip:15,steps:[],used:[],extras:[]},
  {id:'liam_v4_steak_lentilles',slots:[],name:'Steak, lentilles & carottes',kcal:452,prot:34,gluc:40,lip:18,steps:[],used:[],extras:[]},
  {id:'liam_v4_poulet_coco',slots:[],name:'Aiguillettes curry-coco & riz',kcal:900,prot:72,gluc:86,lip:29,steps:[],used:[],extras:[]},
  {id:'liam_v4_salade_mozza',slots:[],name:'Salade tomates-mozzarella & jambon blanc',kcal:547,prot:44,gluc:10,lip:37,steps:[],used:[],extras:[]},
  {id:'liam_v4_soupe_potiron',slots:[],name:'Soupe potiron & tartine de chorizo',kcal:390,prot:17,gluc:21,lip:25,steps:[],used:[],extras:[]},
  {id:'liam_v4_fb_amandes',slots:[],name:'Fromage blanc, amandes & framboises',kcal:308,prot:19,gluc:31,lip:14,steps:[],used:[],extras:[]},
  {id:'liam_v4_shaker_yaourt',slots:[],name:'Shaker whey & yaourt 0%',kcal:162,prot:29,gluc:10,lip:1,steps:[],used:[],extras:[]},
  {id:'liam_v4_carottes_stmoret',slots:[],name:'Carottes bâtonnets & St Morêt',kcal:81,prot:4,gluc:11,lip:3,steps:[],used:[],extras:[]},
  // ── Shaker protéines (gardé en p'tit-déj & collation) ──
  {id:'shaker_whey',slots:['breakfast','snack'],name:'Shaker clear whey post-training',urgent:0,ur:null,time:1,kcal:110,prot:24,gluc:2,lip:0,steps:["30 g whey + 400-500 mL eau froide. Agiter."],used:[{id:'whey',qty:30}],extras:[]},
  {id:'shaker_whey_compote',slots:['breakfast','snack'],name:'Shaker whey fruité & compote',urgent:0,ur:null,time:2,kcal:160,prot:24,gluc:14,lip:0,steps:["Compote + 30 g whey + 300 mL eau froide."],used:[{id:'whey',qty:30},{id:'compotes',qty:1}],extras:[]},
  // ── Repas masqués / références d'historique (slots:[]) ──
  {id:'poke_bowl',slots:[],name:'Poké bowl poulet karaage',kcal:870,prot:39,gluc:115,lip:26,steps:[],used:[],extras:[]},
  {id:'_nuggets_04',slots:[],name:'Nuggets au four (400g)',kcal:860,prot:60,gluc:80,lip:36,steps:[],used:[],extras:[]},
  {id:'_poulet_pane_04',slots:[],name:'Poulet pané au four (500g)',kcal:1050,prot:90,gluc:62,lip:42,steps:[],used:[],extras:[]},
  {id:'_karaage_05',slots:[],name:'Poulet Karaage (150g)',kcal:345,prot:23,gluc:21,lip:18,steps:[],used:[],extras:[]},
  {id:'_poulet_pane_05',slots:[],name:'Poulet pané au four (500g)',kcal:1050,prot:90,gluc:62,lip:42,steps:[],used:[],extras:[]},
  {id:'_diner_pizza_06',slots:[],name:'Dîner pizza — 1 Pizza De la Mama + yaourt 0% + miel + 80g fromage râpé',kcal:1278,prot:57,gluc:116,lip:54,steps:[],used:[],extras:[]},
  {id:'_pates_creme_saumon_250',slots:[],name:'Pâtes crème fraîche & saumon (250g crème)',kcal:970,prot:49,gluc:72,lip:53,steps:[],used:[],extras:[]},
  {id:'_galette_sarrasin_08',slots:[],name:'Galette sarrasin lardons, reblochon, oignons confits, salade + gâteau breton',kcal:1200,prot:60,gluc:110,lip:58,steps:[],used:[],extras:[]},
  {id:'_framboises_07',slots:[],name:'Framboises (~80g)',kcal:26,prot:1,gluc:4,lip:0,steps:[],used:[],extras:[]},
  {id:'_repas_cantine_07',slots:[],name:'Cantine — jambon cru, saumon gratiné pesto/fromage, tartlette chocolat',kcal:990,prot:61,gluc:33,lip:65,steps:[],used:[],extras:[]},
  {id:'pdj_avoine',slots:[],name:'Bowl avoine protéiné',kcal:620,prot:30,gluc:82,lip:20},
  {id:'gratin_gnocchis',slots:[],name:'Gratin gnocchis, jambon & béchamel',kcal:1070,prot:50,gluc:136,lip:29},
  {id:'saumon_riz',slots:[],name:'Saumon poêlé, riz & tomates cerises',kcal:770,prot:37,gluc:83,lip:29},
  {id:'pates_prosciutto_mozza',slots:[],name:'Pâtes prosciutto, mozza & tomates',kcal:900,prot:42,gluc:76,lip:45},
  {id:'omelette',slots:[],name:'Omelette jambon blanc & fromage',kcal:520,prot:38,gluc:1,lip:39},
  {id:'poulet_curry',slots:[],name:'Bowl poulet curry & riz',kcal:810,prot:70,gluc:83,lip:18},
  {id:'dess_yaourt_miel',slots:[],name:'Yaourt 0% & miel',kcal:100,prot:4,gluc:22,lip:0},
];
